// <auto-generated />
namespace BrewApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ACreate_Processed_Brewing_Master_Table : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ACreate_Processed_Brewing_Master_Table));
        
        string IMigrationMetadata.Id
        {
            get { return "201912101732593_ACreate_Processed_Brewing_Master_Table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
