// <auto-generated />
namespace BrewApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class alter_Recipe_Table_Int_to_Double : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(alter_Recipe_Table_Int_to_Double));
        
        string IMigrationMetadata.Id
        {
            get { return "201911280439274_alter_Recipe_Table_Int_to_Double"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
