//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrewApp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CommonDBEntities7 : DbContext
    {
        public CommonDBEntities7()
            : base("name=CommonDBEntities7")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<vw_Brewing_Blotter> vw_Brewing_Blotter { get; set; }
        public virtual DbSet<vw_Employee_Report> vw_Employee_Report { get; set; }
        public virtual DbSet<vw_Order_Blotter> vw_Order_Blotter { get; set; }
        public virtual DbSet<vw_Processed_BrewingMaster> vw_Processed_BrewingMaster { get; set; }
        public virtual DbSet<vw_Recipe_Report> vw_Recipe_Report { get; set; }
        public virtual DbSet<vw_Stock_Report> vw_Stock_Report { get; set; }
    }
}
