//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrewApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Brewing_Blotter
    {
        public int BrewingId { get; set; }
        public int Recipeid { get; set; }
        public string RecipeName { get; set; }
        public double Quantity { get; set; }
        public double ProductionCost { get; set; }
        public System.DateTime BrewingTime { get; set; }
        public string Processed_YN { get; set; }
    }
}
