//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrewApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Employee_Report
    {
        public int EmployeeID { get; set; }
        public string EmployeeName { get; set; }
        public int TotalOrders { get; set; }
        public double TotalOrderAmount { get; set; }
        public double TotalMargin { get; set; }
        public double TotalMargin_Amount { get; set; }
    }
}
