//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrewApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Order_Blotter
    {
        public int OrderId { get; set; }
        public int Recipeid { get; set; }
        public string RecipeName { get; set; }
        public double Order_Quantity { get; set; }
        public double Production_Price { get; set; }
        public double Production_Cost { get; set; }
        public double Customer_Price { get; set; }
        public double Customer_Cost { get; set; }
        public double GST { get; set; }
        public double Margin { get; set; }
        public double Trasportation_Cost { get; set; }
        public string Sales_Person { get; set; }
        public string Customer_Restaurant_Details { get; set; }
        public string Remark { get; set; }
        public System.DateTime Created_At { get; set; }
        public string Created_By { get; set; }
        public double Amount_Paid { get; set; }
        public double Remaining_Amount { get; set; }
    }
}
