//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrewApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Recipe_Report
    {
        public int Recipeid { get; set; }
        public string RecipeName { get; set; }
        public double TotalQuantityProduced { get; set; }
        public double RemainingQuantity { get; set; }
        public double ProductionPrice { get; set; }
        public int TotalOrders { get; set; }
        public double TotalQuantityOrdered { get; set; }
        public double TotalOrderCost { get; set; }
    }
}
